DROP TABLE IF EXISTS config;
DROP TABLE IF EXISTS votes;
DROP TABLE IF EXISTS users;
DROP TABLE IF EXISTS choices;
DROP TABLE IF EXISTS polls;

CREATE TABLE polls
	(p_id INT UNSIGNED NOT NULL AUTO_INCREMENT PRIMARY KEY
	,p_title VARCHAR(255) NOT NULL
	,p_multiple BIT(1) NOT NULL DEFAULT 0
	,p_subonly BIT(1) NOT NULL DEFAULT 0
	,p_visible BIT(1) NOT NULL DEFAULT 0
	) CHARACTER SET = utf8;

CREATE TABLE choices
	(c_id INT UNSIGNED NOT NULL AUTO_INCREMENT PRIMARY KEY
	,_p_id INT UNSIGNED NOT NULL
	,c_bit TINYINT UNSIGNED NOT NULL
	,c_name VARCHAR(255) NOT NULL
	,FOREIGN KEY (_p_id) REFERENCES polls(p_id) ON DELETE CASCADE
	) CHARACTER SET = utf8;

CREATE TABLE users
	(u_id INT UNSIGNED NOT NULL AUTO_INCREMENT PRIMARY KEY
	,__H_oauth BINARY(32) UNIQUE NOT NULL COMMENT 'SHA256 hash of u_oauth field for indexing speed'
	,__H_name BINARY(32) UNIQUE NOT NULL COMMENT 'SHA256 hash of u_name field for indexing speed'
	,u_sub BIT(1) NOT NULL DEFAULT 0
	,u_turbo BIT(1) NOT NULL DEFAULT 0
	,u_oauth VARCHAR(255) NOT NULL
	,u_name VARCHAR(255) NOT NULL
	) CHARACTER SET = ascii COLLATE = ascii_general_ci;

CREATE TABLE votes
	(v_id INT UNSIGNED NOT NULL AUTO_INCREMENT PRIMARY KEY
	,_p_id INT UNSIGNED NOT NULL
	,_u_id INT UNSIGNED NOT NULL
	,v_choice BIGINT UNSIGNED NOT NULL DEFAULT 0
	,v_when TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
	,UNIQUE KEY safety (_p_id, _u_id)
	,FOREIGN KEY (_p_id) REFERENCES polls(p_id) ON DELETE CASCADE
	,FOREIGN KEY (_u_id) REFERENCES users(u_id) ON DELETE CASCADE
	) CHARACTER SET = ascii COLLATE = ascii_general_ci;

CREATE TABLE config
	(_id INT UNSIGNED NOT NULL AUTO_INCREMENT PRIMARY KEY
	,option VARCHAR(255) UNIQUE NOT NULL
	,value VARCHAR(255) NOT NULL
	) CHARACTER SET = ascii COLLATE = ascii_general_ci;
