DROP FUNCTION IF EXISTS poll_find_poll_item;
DELIMITER ~
CREATE DEFINER = 'ferretadmin'@'localhost'
FUNCTION poll_find_poll_item (
	name VARCHAR(255)
)
	RETURNS INT UNSIGNED
	NOT DETERMINISTIC
	READS SQL DATA
	SQL SECURITY DEFINER
BEGIN
	DECLARE id INT UNSIGNED DEFAULT NULL;
	SELECT p_i_id
	  INTO id
	  FROM poll_items
	 WHERE p_i_name = name;
	RETURN id;
END;
~
DELIMITER ;
