CREATE TABLE IF NOT EXISTS polls
	(p_id INT UNSIGNED NOT NULL AUTO_INCREMENT PRIMARY KEY
	,p_title VARCHAR(255) NOT NULL
	,p_maxchoices TINYINT UNSIGNED NOT NULL DEFAULT 0
	,p_subonly CHAR(0) DEFAULT NULL
	,p_open CHAR(0) DEFAULT NULL
	) CHARACTER SET = utf8;

CREATE TABLE IF NOT EXISTS poll_items
	(p_i_id INT UNSIGNED NOT NULL AUTO_INCREMENT PRIMARY KEY
	,p_i_name VARCHAR(255) NOT NULL
	) CHARACTER SET = utf8;

CREATE TABLE IF NOT EXISTS choices
	(c_id INT UNSIGNED NOT NULL AUTO_INCREMENT PRIMARY KEY
	,_p_id INT UNSIGNED NOT NULL
	,_p_i_id INT UNSIGNED NOT NULL
	,c_bit TINYINT UNSIGNED NOT NULL
	,FOREIGN KEY (_p_id) REFERENCES polls(p_id) ON DELETE CASCADE
	,FOREIGN KEY (_p_i_id) REFERENCES poll_items(p_i_id) ON DELETE CASCADE
	) CHARACTER SET = utf8;

CREATE TABLE IF NOT EXISTS users
	(u_id INT UNSIGNED NOT NULL AUTO_INCREMENT PRIMARY KEY
	,__H_oauth BINARY(32) UNIQUE COMMENT 'SHA256 hash of u_oauth field for indexing speed'
	,__H_name BINARY(32) UNIQUE NOT NULL COMMENT 'SHA256 hash of u_name field for indexing speed'
	,u_sub CHAR(0) DEFAULT NULL
	,u_follows CHAR(0) DEFAULT NULL
	,u_oauth VARCHAR(255)
	,u_name VARCHAR(255) NOT NULL
	,u_updated TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
	) CHARACTER SET = ascii COLLATE = ascii_general_ci;

CREATE TABLE IF NOT EXISTS votes
	(v_id INT UNSIGNED NOT NULL AUTO_INCREMENT PRIMARY KEY
	,_p_id INT UNSIGNED NOT NULL
	,_u_id INT UNSIGNED NOT NULL
	,v_choice_0 CHAR(0) DEFAULT NULL
	,v_choice_1 CHAR(0) DEFAULT NULL
	,v_choice_2 CHAR(0) DEFAULT NULL
	,v_choice_3 CHAR(0) DEFAULT NULL
	,v_choice_4 CHAR(0) DEFAULT NULL
	,v_choice_5 CHAR(0) DEFAULT NULL
	,v_choice_6 CHAR(0) DEFAULT NULL
	,v_choice_7 CHAR(0) DEFAULT NULL
	,v_choice_8 CHAR(0) DEFAULT NULL
	,v_choice_9 CHAR(0) DEFAULT NULL
	,v_choice_a CHAR(0) DEFAULT NULL
	,v_choice_b CHAR(0) DEFAULT NULL
	,v_choice_c CHAR(0) DEFAULT NULL
	,v_choice_d CHAR(0) DEFAULT NULL
	,v_choice_e CHAR(0) DEFAULT NULL
	,v_choice_f CHAR(0) DEFAULT NULL
	,v_choice_g CHAR(0) DEFAULT NULL
	,v_choice_h CHAR(0) DEFAULT NULL
	,v_choice_i CHAR(0) DEFAULT NULL
	,v_choice_j CHAR(0) DEFAULT NULL
	,v_choice_k CHAR(0) DEFAULT NULL
	,v_choice_l CHAR(0) DEFAULT NULL
	,v_choice_m CHAR(0) DEFAULT NULL
	,v_choice_n CHAR(0) DEFAULT NULL
	,v_choice_o CHAR(0) DEFAULT NULL
	,v_choice_p CHAR(0) DEFAULT NULL
	,v_choice_q CHAR(0) DEFAULT NULL
	,v_choice_r CHAR(0) DEFAULT NULL
	,v_choice_s CHAR(0) DEFAULT NULL
	,v_choice_t CHAR(0) DEFAULT NULL
	,v_choice_u CHAR(0) DEFAULT NULL
	,v_choice_v CHAR(0) DEFAULT NULL
	,v_choice_w CHAR(0) DEFAULT NULL
	,v_choice_x CHAR(0) DEFAULT NULL
	,v_choice_y CHAR(0) DEFAULT NULL
	,v_choice_z CHAR(0) DEFAULT NULL
	,v_when TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
	,IPv6 BIGINT UNSIGNED COMMENT 'If null, address is IPv4'
	,IPv4 BIGINT UNSIGNED NOT NULL
	,UNIQUE KEY safety (_p_id, _u_id)
	,FOREIGN KEY (_p_id) REFERENCES polls(p_id) ON DELETE CASCADE
	,FOREIGN KEY (_u_id) REFERENCES users(u_id) ON DELETE CASCADE
	) CHARACTER SET = ascii COLLATE = ascii_general_ci;

CREATE TABLE IF NOT EXISTS config
	(_id INT UNSIGNED NOT NULL AUTO_INCREMENT PRIMARY KEY
	,option VARCHAR(255) UNIQUE NOT NULL
	,value VARCHAR(255) NOT NULL
	) CHARACTER SET = ascii COLLATE = ascii_general_ci;

CREATE TABLE IF NOT EXISTS permissions
	(_id INT UNSIGNED NOT NULL AUTO_INCREMENT PRIMARY KEY
	,_u_id INT UNSIGNED UNIQUE NOT NULL
	,poll_create CHAR(0) DEFAULT NULL
	,FOREIGN KEY (_u_id) REFERENCES users(u_id) ON DELETE CASCADE
	) CHARACTER SET = ASCII COLLATE = ascii_general_ci;
